default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres   # ← ここは自分のPostgreSQLユーザー名に
  password:                    # ← パスワードがあるなら記入
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: valorant_picker_development

test:
  <<: *default
  database: valorant_picker_test

production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    database: valorant_picker_test
    

  cable:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    database: valorant_picker_test

  queue:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    database: valorant_picker_test

  cache:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
    database: valorant_picker_test
